app/family/__init__.py
from flask import Blueprint

bp = Blueprint('family', __name__)


from app.family import routes

app/family/routes.py
from flask import render_template, request, redirect, url_for
# from app.register import bp
from flask_login import login_required, current_user
from datetime import date
from app.family import bp
from app import db
from app.user import User
from app.models.register import Member
# from app.models.deposit import Deposit
from app.models.community_event import CommunityEvent
from app.models.child import Child
from app.models.wife import Wife
from datetime import date

@bp.route('/')
@login_required
def index():
    user = User.query.get_or_404(current_user.id)
    return render_template("family/index.html", user = user)


@bp.route('/<int:depo_id>/')
def family(depo_id):
    register = Member.query.get_or_404(depo_id)
    return render_template('family/family.html', register = register)

@bp.route('/<int:depo_id>/edit', methods=('POST', 'GET'))
def edit(depo_id):
    register = Member.query.get_or_404(depo_id)
    if request.method == 'POST':
        firstname=request.form['firstname']
        lastname=request.form['lastname']
        date_of_birth=request.form['date_of_birth']
        phone_num=request.form['phone_num']
        id_number=request.form['id_number']

        register.firstname = firstname
        register.lastname = lastname
        register.date_of_birth = date_of_birth
        register.contact = contact
        register.id_number = id_number

        db.session.add(register)
        db.session.commit()
        return redirect(url_for('family.family', depo_id=register.id))
    return render_template('register/edit.html', register = register, family = register)

@bp.route('/<int:depo_id>/create_wife', methods=('POST', 'GET'))
def create_wife(depo_id):
    register = Member.query.get_or_404(depo_id)
    if request.method == 'POST':
        new_wife = Wife(firstname = request.form['firstname'], lastname = request.form['lastname'], surname = request.form['surname'], phone_num = request.form['phone_num'], date_of_birth = request.form['date_of_birth'], id_number=request.form['id_number'],member = register)
        db.session.add(new_wife)
        db.session.commit()
        return redirect(url_for('family.family', depo_id = register.id))
    return render_template('register/create.html', register=register)

@bp.route('/<int:depo_id>/<int:wife_id>/create_child', methods=('POST', 'GET'))
def create_child(depo_id, wife_id):
    register = Member.query.get_or_404(depo_id)
    wife = Wife.query.get_or_404(wife_id)
    if request.method == 'POST':
        child = Child(
            firstname=request.form['firstname'],
            lastname=request.form['lastname'],
            surname=request.form['surname'],
            phone_num=request.form['phone_num'],
            id_number=request.form['id_number'],
            date_of_birth=request.form['date_of_birth'],
            wife = wife
        )
        db.session.add(child)
        db.session.commit()
        return redirect(url_for('family.family', depo_id = register.id))
    return render_template('register/create.html', register=register, wife = wife)

@bp.post('/<int:depo_id>/<int:del_id>/delete')
def delete(depo_id, del_id):
    register = Member.query.get_or_404(depo_id)
    wife = Wife.query.get_or_404(del_id)
    for child in wife.child:
        db.session.delete(child)
    db.session.delete(wife)
    db.session.commit()
    return redirect(url_for('family.family', depo_id = register.id))

@bp.route('/<int:depo_id>/<int:edit_id>/edit_wife', methods=('POST','GET'))
def edit_wife(depo_id, edit_id):
    register = Member.query.get_or_404(depo_id)
    wife = Wife.query.get_or_404(edit_id)
    if request.method == 'POST':
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        surname = request.form['surname']
        phone_num = request.form['phone_num']
        id_number = request.form['id_number']
        date_of_birth = request.form['date_of_birth']
        
        wife.firstname = firstname
        wife.lastname = lastname
        wife.surname = surname
        wife.phone_num = phone_num
        wife.id_number = id_number
        wife.date_of_birth = date_of_birth

        db.session.add(wife)
        db.session.commit()

        return redirect(url_for('family.family', depo_id = register.id))
    return render_template('register/edit.html', register = wife, family = register)

@bp.route('/<int:depo_id>/<int:edit_id>/<int:child_id>/edit_child', methods=('POST','GET'))
def edit_child(depo_id, edit_id, child_id):
    register = Member.query.get_or_404(depo_id)
    wife = Wife.query.get_or_404(edit_id)
    child = Child.query.get_or_404(child_id)
    if request.method == 'POST':
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        surname = request.form['surname']
        phone_num = request.form['phone_num']
        id_number = request.form['id_number']
        date_of_birth = request.form['date_of_birth']
        
        child.firstname = firstname
        child.lastname = lastname
        child.surname = surname
        child.phone_num = phone_num
        child.id_number = id_number
        child.date_of_birth = date_of_birth

        db.session.add(child)
        db.session.commit()

        return redirect(url_for('family.family', depo_id = register.id))
    return render_template('register/edit.html', register = child, family = register)

@bp.route('/<int:depo_id>/<int:child_id>/edit_child', methods=('POST','GET'))
def editchild(depo_id, child_id):
    register = Member.query.get_or_404(depo_id)
    child = Child.query.get_or_404(child_id)
    if request.method == 'POST':
        firstname = request.form['firstname']
        lastname = request.form['lastname']
        surname = request.form['surname']
        phone_num = request.form['phone_num']
        id_number = request.form['id_number']
        date_of_birth = request.form['date_of_birth']
        
        child.firstname = firstname
        child.lastname = lastname
        child.surname = surname
        child.phone_num = phone_num
        child.id_number = id_number
        child.date_of_birth = date_of_birth

        db.session.add(child)
        db.session.commit()

        return redirect(url_for('family.family', depo_id = register.id))
    return render_template('register/edit.html', register = child, family = register)

@bp.post('/<int:depo_id>/delete/')
def delete_family(depo_id):
    depo = Deposit.query.get_or_404(depo_id)
    register = Member.query.get_or_404(depo_id)
    for man in depo.family:
        for child in man.child:
            db.session.delete(child)
    for wife in man.wife:
        for child_ in wife.child:
            db.session.delete(child_)
        db.session.delete(wife)
    
    db.session.delete(man)
    db.session.delete(depo)
    db.session.commit()
    return redirect(url_for('family.index'))


# @bp.route('/<int:depo_id>/age')
# def date_of_b(depo_id):
#         deposit = Deposit.query.get_or_404(depo_id)
#         register = Member.query.get_or_404(depo_id)
#         today = date.today()
#         d3 = today.strftime("%m-%d-%y")
#         d4 = register.date_of_birth
#         # d4 = d_4.strftime(d_4"%m-%d-%Y")
#         # print("d3 =", d3)
#         age = d3.year - d4.year - ((today.month, today.day) < (d4.month, d4.day))
@bp.route('/birthday')
@login_required
def contact():
    user = User.query.get_or_404(current_user.id)
    member = user.family
    if member:
        age_list = []
        for birthday in member:
            today = date.today()
            age = today.year - birthday.date_of_birth.year - ((today.month, today.day) < (birthday.date_of_birth.month, birthday.date_of_birth.day))
            age_list.append(age)


#    return render_template('contact.html', member = member, age = age_list)
    return render_template("family/birthday.html", member = member, register = register, age=age)

app/templates/family/birthday.html
{% extends "base_f/base.html" %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}

{% block content %}
<span class="title"><h1>{% block title %} Fetha Members {% endblock %}</h1></span>    
<div id="myUL">
    {% for member in member %}
    <li class="content">
        <p>{{member.first_name}}
        {{member.last_name }}
        <p>Date of birth: {{member.date_of_birth}}</p>
               
        {% if age %}
        <p>Age: {{ age[member.id-1:member.id] }} years</p> 
        {%endif%}
    <hr style="color: greenyellow;">
    <br>
    </li>
    {% endfor %}
    <br>
</div>
{% endblock %}

app/templates/family/create_child.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <h1 style="width: 100%">{% block title %} Add Child {% endblock %}</h1>
    <form method="post">
        <p>
            <label for="firstname">First Name</label>
            <input type="text" name="firstname"
                   placeholder="First Name">
            </input>
        </p>

        <p>
            <label for="lastname">Last Name</label>
            <input type="text" name="lastname"
                   placeholder="Last Name">
            </input>
        </p>

        <p>
            <label for="date_of_birth">Date of birth</label>
            <input type="date" name="date_of_birth"
                   placeholder="Date of birth">
            </input>
        </p>

        <p>
            <!-- <button type="submit" href="{{url_for('register.index')}}">Save and close </button> -->
            <button type="submit">Save</button>
        </p>
    </form>
{% endblock %}

app/templates/family/create_wife.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <h1 style="width: 100%">{% block title %} Add Wife {% endblock %}</h1>
    <form method="post">
        <p>
            <label for="firstname">First Name:</label>
            <input type="text" name="firstname"
                   placeholder="First Name">
            </input>
        </p>

        <p>
            <label for="lastname">Last Name:</label>
            <input type="text" name="lastname"
                   placeholder="Last Name">
            </input>
        </p>

        <p>
            <label for="id_number">ID:</label>
            <input type="number" name="id_number"
                   placeholder="id number">
            </input>
        </p>

        <p>
            <label for="date_of_birth">Date of Birth:</label>
            <input type="date" name="date_of_birth"
                   placeholder="Date of birth">
            </input>
        </p>

        <p>
            <button type="submit">Save</button>
        </p>
    </form>
{% endblock %}

app/templates/family/edit.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<h1 style="width: 100%">{% block title %} Edit Name{% endblock %}</h1>
<form method="post">
    <div class="row">
        <div class="col-25">
            <label for="firstname">First Name:</label>
        </div>
        <div class="col-75">
        <input type="text" id="firstname" name="firstname" value="{{register.firstname}}" placeholder="First Name">
        </div>
    </div>
    <div class="row">
        <div class="col-25">
            <label for="lastname">Last Name:</label>
        </div>
        <div class="col-75">
            <input type="text" id="lastname" name="lastname" value="{{register.lastname}}" placeholder="Last Name"><br>
        </div>
    </div>

    <div class="row">
        <div class="col-25">
            <label for="date_of_birth">Date of birth: </label>
        </div>
        <div class="col-75">
            <input type="date" id="date_of_birth" value="{{register.date_of_birth}}" name="date_of_birth" placeholder="date_of_birth">
        </div>
    </div>
    <div class="row">
        <div class="col-25">
            <label for="contact">Contact: </label>
        </div>
        <div class="col-75">
            <input type="text" value="{{register.contact}}" id="contact" name="contact" placeholder="Contact">
        </div>
    </div>
    <!-- {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %} -->

    <div class="row">
        <div class="col-25">
            <label for="id_number">ID Number: </label>
        </div>
        <div class="col-75">
            <input type="number" id="id_number" name="id_number" value="{{register.id_number}}" placeholder="id number">
        </div>
    </div>
    
    <p> <button type="submit">Save</button>
    </form>
    <a href="{{url_for('family.family', depo_id = register.id)}}"><button>Cancel</button></a></p>
{% endblock %} 

app/templates/family/edit_child.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<h1 style="width: 100%">
        {% block title %} Edit Child
        {% endblock %}
</h1>
    
    
    <form method="post">
        <p>
            <label for="firstname">First Name:</label>
            <input type="text" name="firstname"
                   value="{{ child.firstname }}"
                   placeholder="First name">
            </input>
        </p>
        
        <p>
            <label for="lastname">Last Name:</label>
            <input type="text" name="lastname"
                   value="{{ child.lastname }}"
                   placeholder="Last name">
            </input>
        </p>

        <p>
            <label for="date_of_birth">Date of birth:</label>
            <input type="date" name="date_of_birth"
                    value="{{ child.date_of_birth}}"
                   placeholder="Date of birth">
            </input>
        </p>

        <p>
            <button type="submit">Edit</button>
            
            <button><a href="{{url_for('family.family', depo_id = register.id)}}">cancel</a></button>
        </p>
    </form>
{% endblock %} 

app/templates/family/edit_wife.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<h1 style="width: 100%">
        {% block title %} Edit wife
        {% endblock %}
</h1>
    <form method="post">
        <p>
            <label for="firstname">First Name:</label>
            <input type="text" name="firstname"
                   value="{{ wife.firstname }}"
                   placeholder="First name">
            </input>
        </p>
        
        <p>
            <label for="lastname">Last Name:</label>
            <input type="text" name="lastname"
                   value="{{ wife.lastname }}"
                   placeholder="Last name">
            </input>
        </p>
        <p>
            <label for="id_number">ID:</label>
            <input type="number" name="id_number"
                    value="{{ wife.id_number }}"
                   placeholder="id number">
            </input>
        </p>

        <p>
            <label for="date_of_birth">Date of firth:</label>
            <input type="date" name="date_of_birth"
                    value="{{ wife.date_of_birth}}"
                   placeholder="Date of birth">
            </input>
        </p>

        <p>
            <button type="submit">Edit</button>
            
            <button><a href="{{url_for('family.family', depo_id = register.id)}}">cancel</a></button>
        </p>
    </form>
{% endblock %} 

app/templates/family/family.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<div class="register" style="width: 45%;color: black;">
    <span class="title"><h1>{% block title %} {{ register.firstname }}'s Family {% endblock %}</h1></span>
<br><br>
    </br>
    <a href="{{url_for('register.deposit', depo_id = register.id)}}">
        <button>Profile</button>
    </a>
    <form method="POST" style="float:right;"
            action="{{ url_for('family.delete_family',
                                depo_id = register.id) }}">
            <img class="image" style="border-radius: 0%;" src="/static/photos/Delete.jpg" alt="delete"onclick="return confirm('Are you sure you want to delete this entry?')">
            <!-- <input style="font-size: smaller; background-color: coral;" type="submit" value="Delete Family" -->
                <!-- onclick="return confirm('Are you sure you want to delete this entry?')"> -->
    </form><hr>
    <div class="register" id="myUL">
        <li class="register">
            <p>
            Name: {{register.firstname}} {{ register.lastname }}<br>
            Id Number: {{register.id_number}}<br>
            Phone Number: {{register.phone_num}}<br>
            <!-- <p>Date of birth: {{ register.date_of_birth }}</p> -->
            Created at: {{ register.created_at }}</p>
            <a href="{{url_for('family.edit',depo_id=register.id)}}"><button>Edit Name</button></a>
            <a href="{{ url_for('family.create_wife', depo_id=register.id)}}"><button>New Wife</button></a>
            <a href="{{ url_for('register.create_child', depo_id=register.id)}}"><button>New Child</button></a>
        </li>
        <hr>
        <div class="register" id="myUL">
            <li class="register">
                {% for child in register.child %}
                <h6>Child</h6>

                <p>
                Name: {{ child.firstname }} {{ child.lastname }} {{ child.surname }}<br>
                Phone Number {{ child.phone_num }}<br>
                Id Number: {{ child.id_number }}<br></p>
                <!-- <p>Date of birth: {{ child.date_of_birth}}<br></p> -->

                <a href="{{url_for('family.editchild',depo_id=register.id, child_id = child.id )}}"><button>Edit child</button></a>
                <hr>
                {% endfor %}
            </li>
        </div>
        <div class="register" id="myUL">
            <!-- <h3>Family</h3> -->
        
        {% for wife in register.wife %}
        <h6>Wife</h6>
        <li class="register">
            <p>
            Name: {{ wife.firstname }} {{ wife.lastname }} {{ wife.lastname }}<br>
            Phone Number: {{wife.phone_num}}<br>
            Id Number: {{wife.id_number}}<br></p>

            <!-- <p>Date of birth: {{ wife.date_of_birth}}</p> -->

            <a href="{{ url_for('family.edit_wife',
            depo_id = register.id, edit_id=wife.id) }}"><button>Edit Wife</button></a>

            <a href="{{ url_for('family.create_child', depo_id=register.id, wife_id = wife.id)}}"><button> New Child</button></a>
            </form>
            <form method="POST"
                action="{{ url_for('family.delete',
                                    depo_id = register.id, del_id=wife.id) }}">
                <input type="submit" value="Delete Wife"
                    onclick="return confirm('Are you sure you want to delete this entry?')">
            </form>
            <hr>
        </li>
        </div>
        <div class="register" id="myUL">
            {% for child in wife.child %}
            <h6>Child</h6>
            <li class="register">
                <p>
                    Name: {{ child.firstname }} {{ child.lastname }} {{ child.surname }}<br>
                    Phone Number {{ child.phone_num }}<br>
                    Id Number: {{ child.id_number }}<br>
                </p>
            <a href="{{url_for('family.edit_child',depo_id=register.id, edit_id = wife.id, child_id = child.id )}}"><button>Edit child</button></a>
            </li>
    
            {% endfor %}
        </div>
        {% endfor %}
</div>
{% endblock %} 

app/templates/family/index.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<span class="title"><h1>{% block title %} Family {% endblock %}</h1></span>
<div class="content">
        <div id="myUL">
            {% for father in user.family %}
            <li class="register">
                <p>Name:<a href="{{url_for('family.family', depo_id = father.id)}}">{{ father.firstname}} {{ father.lastname }}</a></p>
                <p>{{father.id_number}}</p>
                <div class="content">
                    <p>Created at: {{ father.created_at }}</p></br>
                </div>
            </li>
            {% endfor %}
        </div><hr>
</div>
{% endblock %}