app/models/deposit.py
from app import db
from sqlalchemy.sql import func
from app.models.cont_depo import cont_depo

class Deposit(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    amount = db.Column(db.Integer)
    reg_id = db.Column(db.Integer, db.ForeignKey('register.id'))
    created_at = db.Column(db.DateTime(timezone=True), server_default=func.now())
    contribute = db.relationship('Contribute',  secondary=cont_depo, backref='deposit')

    def __repr__(self):
        return f'<Amount {self.amount} >'

app/deposit/__init__.py
from flask import Blueprint

bp = Blueprint('deposit', __name__)


from app.deposit import routes

app/deposit/routes.py
from flask import render_template, request, redirect, url_for,flash
from app.deposit import bp
from flask_login import login_required, current_user
from app import db
from app.user import User
from app.models.register import Member
# from app.models.deposit import Deposit
from app.models.community_event import CommunityEvent
from app.models.wife import Wife
from app.models.child import Child
from app.models.contribute import Contribution
from app.models.payments import Payment
@bp.route('/')
@login_required
def index():
    user = User.query.get_or_404(current_user.id)
    register = user.family
    return render_template("deposit/index.html", user = user, register = register)

@bp.route('/<int:depo_id>/')
def deposit(depo_id):
    # depo = Deposit.query.get_or_404(depo_id)
    register = Member.query.get_or_404(depo_id)
    # depo_id = register.deposit.id
    deposit = register.contribute
        

    total = 0
    for acc in register.contribute:
        total += acc.amount
    
    return render_template('deposit/deposit.html', register = register, total = total, deposit = deposit)

@bp.route('/<int:depo_id>/amount', methods=('POST', 'GET'))
def amount(depo_id):
    user = User.query.get_or_404(current_user.id)
    level = Payment
    register = Member.query.get_or_404(depo_id)

    if request.method == 'POST':
        amount = Contribution(amount = request.form['amount'], payment_type = request.form['payment'], transaction_ref=request.form['transaction_ref'], propose = request.form.get('propose'), member = register, user = user)        
        
        community = CommunityEvent.query.filter_by(id = amount.propose).first()
        if not community:
            flash("Error, Select Community Event!")
            return redirect(url_for('deposit.amount', depo_id=register.id))
        # propose = amount.propose
        # if community:
        #     # amount.propose.append(community)
            # event.register.append(community)
        db.session.add(amount)
        db.session.commit()
        
        return redirect(url_for('register.deposit', depo_id=register.id))
    return render_template("deposit/amount.html", register = register, user = user, level = level)

app/templates/deposit/amount.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <h1 style="width: 100%">
        {% block title %} Enter amount
        {% endblock title  %}
    </h1>
    <body>
        <p>
        <button><a style="font-size: 8px;" href="{{url_for('register.deposit', depo_id=register.id)}}"> <- Back</a></button>
        </p>
        <form method="post">
        <div>
        <p>
            <label for="amount">Ksh:</label>
            <input type="number" name="amount"
                   placeholder="Ksh.">
            </input>
        </p>
        <div class="field">
                <select id="payment" name="payment" placeholder="Payment Type"style="width:15%" autofocus="">
                    {% for level in level %}
                    <option value="{{level.name}}">{{level.name}}: {{level.value}}</option>
                    {% endfor %}
                </select>
        </div>
        
        <div class="row">
            <div class="col-25">
                <label for="transaction_ref">Transaction Reference: </label>
            </div>
            <div class="col-75">
                <input type="text" id="transaction_ref" value="{{register.firstname}} {{register.lastname}}" name="transaction_ref" placeholder="Name">
            </div>
        </div>
        
        <div class="field">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div style="color: black;font-size: small;" class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
            {% for cont in user.event %}
            <label>
                <input type="checkbox"id="myCheck" name="propose" value="{{cont.id}}" >{{cont.name}}
            </label>
            {% endfor %}
            
        </div>
        
        <p>
        <button type="submit" style="font-size: 8px;">Send</button>
        <!-- <button><a style="font-size: 8px;" href="{{url_for('register.deposit', depo_id=register.id)}}">Cancel</a></button> -->
        </p>
    </div>
    </form>
    </body>
    {% endblock %}

app/templates/deposit/deposit.html
{% from 'macros.html' import display_tags %}
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<span class="title"><h1>{% block title %} The Details Page {% endblock %}</h1></span>
<div class="content">
    <div class="live-search-list" type="None">
            <div class="register">
                <a href="{{url_for('register.deposit', depo_id = register.id)}}">
                    <button>Profile</button>
                </a>
            <p class="title">
                {{ register.firstname}} {{ register.lastname }}
            </p>
            <div class="content">
                
                Date of birth {{ register.date_of_birth }}<br>
                Date created: {{ register.created_at }}<br>
                <br>
                Ksh. {{ total }}</br></dr>
                <div class="content">
                {% for deposit in deposit %}
                {{ display_tags(deposit)}}<br>{{deposit.amount}}||</br>
                {% endfor %}
                </div>
                <hr>                
            </div>
            </div>
    </div>
</div>
{% endblock %}

app/templates/deposit/edit.html
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
    <h1 style="width: 100%">
        {% block title %} Edit amount
        {% endblock title  %}
    </h1>
    <body>
        <form method="post">
        <p>
            <label for="amount">Ksh:</label>
            <input type="number" name="amount"
                   value="{{ deposit.amount }}"
                   placeholder="Ksh.">
            </input>
        </p>
        <p>
            <button type="submit">Edit</button>
            
            <button><a href="{{url_for('register.deposit', depo_id=register.id)}}">cancel</a></button>
        </p>
    </form>
    </body>
    {% endblock %}

app/templates/deposit/index.html
{% from 'macros.html' import display_tags %}
{% extends 'base_f/base.html' %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/style.css')}}">
{% endblock %}
{% block content %}
<span class="title"><h1>{% block title %} Deposits {% endblock %}</h1></span>

<div id="myUL" class="register">
        {% for father in register %}
        <div class="content" id="myUL">
            <li>    
                <p>Name:<a href="{{url_for('deposit.deposit', depo_id = father.id)}}">{{ father.firstname}} {{ father.lastname }}</a></p>
                <form action="/contribution" method="post">
                <div class="content">
                {%for deposit in father.depo_id %}
        
                {{ display_tags(deposit) }}
                {%endfor%}
            </form>
            </div>
            </li>
        </div>
        {%endfor%}
    </div>
{% endblock %}