app/account/__init__.py
from flask import Blueprint

bp = Blueprint('account', __name__)


from app.account import routes

app/auth.py
from flask import Blueprint, render_template, redirect, url_for, request, flash,session
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import login_user, login_required, logout_user, current_user
from .user import User
from .image import Images
from . import db
from .level import AccessLevel
auth = Blueprint('auth', __name__)

@auth.route('/login')
def login():
    level = AccessLevel
    return render_template('login.html', level = level)

@auth.route('/login', methods=['POST'])
def login_post():
    # log in code goes here
    role = request.form.get('role')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(role=role).first()

    # check if the user actually exists
    # take the user-supplied password, hash it, and compare it to the hashed password in the database
    if not user or not check_password_hash(user.password, password):
        flash('Please check your login details and try again.')
        return redirect(url_for('auth.login')) # if the user doesn't exist or password is wrong, reload the page

    # if the above check passes, then we know the user has the right credentials
    login_user(user, remember=remember)
    return redirect(url_for('main.profile'))

@auth.route('/signup')
def signup():
    level = AccessLevel
    return render_template('signup.html', level=level)

@auth.route('/signup', methods=['POST'])
def signup_post():
    #code to validate and user to database goes here
    surname = request.form.get('surname')
    first_name = request.form.get('first_name')
    last_name = request.form.get('last_name')
    phone_num = request.form.get('phone_num')
    username = request.form.get('username')
    role = request.form.get('role')
    password = request.form.get('password')

    user = User.query.filter_by(role=role).first() # if this returns a user, then the email already exists in database

    if user: # if a user is found, we want to redirect back to signup page so user can try again
        flash('User address already exists')
        return redirect(url_for('auth.signup'))

    # create a new user with the form data. Hash the password so the plaintext version isn't saved.
    new_user = User(surname=surname, first_name=first_name, phone_num=phone_num, password=generate_password_hash(password, method='sha256'), role=role, username=username)

    # add the new user to the database
    db.session.add(new_user)
    db.session.commit()

    return redirect(url_for('auth.login'))

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('main.index'))

# @auth.route('/<int:user_id>/changePassword', methods=['POST', 'GET'])
# @login_required
# def password(user_id):
#     user = User.query.get_or_404(user_id)
#     #code to validate and user to database goes here
#     password = generate_password_hash(password=user.password)
#     passwrd = check_password_hash(user.password, password)
#     if request.method == 'POST':
#         passwords = request.form.get('password')
#         user.password = passwords

#         db.session.add(user)
#         db.session.commit()
#         return redirect(url_for('main.profie'))
#     return render_template('password.html', user = user, passwrd = passwrd)


# @auth.route("/passwordchange", methods=["GET", "POST"])
# @login_required
# def changepassword():
#     # import mysql.connector as sqltor
#     # mycon=sqltor.connect(host="localhost",user="root",passwd="root",database="gamerock")
#     # db=mycon.cursor
#     """"Change users' password"""

#     user = User.query.get_or_404(current_user.id)
#     if request.method == "POST":
#         newPassword = request.form.get("newPassword")
#         newConfirmation = request.form.get("newConfirmation")

#         # Ensure that the user has inputted
#         if (not newPassword) or (not newConfirmation):
#             return apology("Please fill all of the provided fields!", 400)

#         # Check to see if password confirmation were the same or not
#         if newPassword != newConfirmation:
#             return apology("password did not match with password (again)", 400)
        
#         user_id = user.id
        
#         newHash = generate_password_hash("newPassword")

#         # user.password = newHash
#         # db.session.add(user)
#         # db.session.commit()
#         db.execute("UPDATE user SET hash = ? WHERE id = ?", newHash, user_id)
#         passwordChange = check_password_hash(newHash, newPassword)

#         print(f'\n\n{passwordChange}\n\n')
#         return redirect("/login")
#     else:
#         return render_template("password.html")
    

app/home/__init__.py
from flask import Blueprint

bp = Blueprint('home', __name__)

from app.home import routes

app/home/routes.py
from flask import render_template, url_for
from flask_login import login_required, current_user
from app.home import bp
from app import db
from app.user import User

@bp.route('/')
@login_required
def home():
    return render_template("home.html", contact = current_user.phone_num, email = current_user.role)

app/main.py
import os
from flask import Blueprint, render_template, request, redirect, flash, url_for, jsonify, current_app,Response, send_file
from flask_login import login_required, current_user
from werkzeug.utils import secure_filename
from . import db
from .image import Images
from .user import User
import os
import base64
import io

main = Blueprint('main', __name__)

@main.route('/')
@login_required
def index():
    return render_template('home.html', name = current_user.username, contact = current_user.phone_num, email = current_user.role.name)

@main.route('/profile')
@login_required
def profile():
    user = User.query.get_or_404(current_user.id)
    img = user.image
    if not img:
        return redirect(url_for('main.upload_file'))
    
    # img=Images.query.filter_by(id = 1).order_by(Images.id.desc()).first_or_404()
    image_list = []
    # read image data from db back to form a rendable in html
    for img in img:
        image = base64.b64encode(img.image).decode('ascii')
        image_list.append(image)
    
    return render_template('profile.html', name = current_user.username, contact = current_user.phone_num, email = current_user.role, image_list=image_list, img = img)

upload_folder = os.path.join('static')

def gen_file_name(filename):
    """
    If file was exist already, rename it and return a new name
    """
    filename = current_app.config['UPLOAD_FOLDER'] 

    return filename

@main.route('/upload', methods=['GET', 'POST'])
def upload_file():
    user = User.query.get_or_404(current_user.id)
   
    if request.method == 'POST':
        file = request.files['image']
        newFile=Images(
        name=file.filename,
        image=file.read(),
        user = user
        )        
        db.session.add(newFile)
        db.session.commit()
        return redirect(url_for('main.profile'))
    return render_template('other.html')

@main.route('/image')
def get_images():
    images = db.session.query(Images).all()
    image_list = []
    # read image data from db back to form a rendable in html
    for img in images:
        image = base64.b64encode(img.image).decode('ascii')
        image_list.append(image)
    return render_template('image.html', image_list=image_list)

# @main.route('/download')
# def download():
#     file_data = Images.query.filter_by(id=1).first()

#     return send_file(io.BytesIO(file_data.image),
# attachment_filename='user.jpg',as_attachment=True) 

@main.route('/<int:img_id>/new_upload', methods=['GET', 'POST'])
def uploadNew(img_id):
    user = User.query.get_or_404(current_user.id)
    image = Images.query.get_or_404(img_id)
    if request.method == 'POST':
        file = request.files['image']
        # newFile=Images(
        # name=file.filename,
        # image=file.read()
        # )
        image.name = file.filename
        image.image = file.read()

        db.session.add(image)
        db.session.commit()
        return redirect(url_for('main.profile'))
    return render_template('other.html')

app/register/__init__.py
from flask import Blueprint

bp = Blueprint('register', __name__)


from app.register import routes

app/templates/add.html
{% extends 'bootstrap/base.html' %}
{% import  'bootstrap/wtf.html' as wtf %}

{% block title %}Add A New Cafe{% endblock %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('.static', filename='css/styles.css')}}">
{% endblock %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8">

      <h1>Add a new Account into the database</h1>
      {{ wtf.quick_form(form, novalidate=True) }}

	  <p class="space-above"><a href="#">See all cafes</a></p>

    </div>
  </div>
</div>

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html>

<head>
    <title>Gamerock</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    
    <link rel="stylesheet" href="{{ url_for('static', filename='css/header.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/footer.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/image.css') }}">
    <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
</head>
<body>
</header>
    <nav style="justify-content: center; font-size: medium;">
        
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('main.profile') }}" class="navbar-item">
            <u style="font-size: medium;">Profile</u>
        </a>
        {% endif %}
        {% if not current_user.is_authenticated %}
        <a href="{{ url_for('auth.login') }}" class="navbar-item">
        <u style="font-size: medium;">Login</u>
        </a>
        <a href="{{ url_for('auth.signup') }}" class="navbar-item">
        <u style="font-size: medium;">Sign Up</u>
        </a>
        {% endif %}
        {% if current_user.is_authenticated %}
        <a href="{{ url_for('auth.logout') }}" class="navbar-item" style="float: right; display: inline;">
        <u style="font-size: medium;">Logout</u>
        </a>
        {% endif %}
    </nav>
</header>
<hr>
    {% extends "bootstrap/base.html" %}
    <div class="content">
        <div class="container has-text-centered">
           {% block content %}
           {% endblock %}
        </div>
    </div>
</body>
</html>

app/templates/home.html
{% extends "base.html" %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
{% endblock %} 
<span class="title"><h1>{% block title %} Welcome to Gamerock {% endblock %}</h1></span>

{% block content %}
    <body>
        <p style="color: green; margin-left: 45%;">Gamerock</p>
        <img src="/static/photos/africa.jpg" alt="Gamerock" style="margin-left: 25%;height: 450px; width: 450px; justify-content: center; display: flex;">
        <p style="color: black;margin-left: 25%;margin-right: 25%;">
        Court attention at all cost Everything is judge by its appearance, What is unseen counts for nothing.
        Never let yourself get lost in the crowd then, or buried in oblivion stand out. Be conspirous at all cost. Make yourself a magnet of attention by apperaring larger, more colorful, more mysterious than the bland and timid masses.
        </p>
        <hr>
        <div style="width: 65%;" class="content">
        Name: {{ name }}<br>
        Role: {{ email }}<br> 
        Contact: {{ contact }} <br>
        </div>
        <a href="{{url_for('register.index')}}"><button>Open</button></a><br>
    </body>
    {% endblock %}

app/templates/image.html
{% extends "base.html" %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/image.css')}}">
{% endblock %}

{% block content %}
<ul>
  {% if image_list|length == 0 %}
  <p>Add some Images to the Gallery</p>
  {% else %}
  {% for image in image_list %}
  <li>
  <img src="data:;base64,{{image}}" style="height: 200px;"/>
  </li>
  {%endfor%}
  {%endif%}
  </ul>
{% endblock%}

app/templates/login.html
{% extends "base.html" %}
<span class="title"><h1>{% block title %} login {% endblock %}</h1></span>

{% block content %}
<div class="column is-4 is-offset-4"style="justify-content: space-between;">
    <br><br>
    <h3 class="title">Login</h3>
    <div class="box">
    {% with messages = get_flashed_messages() %}
    {% if messages %}
    <div class="notification is-danger">
        {{ messages[0] }}
    </div>
    {% endif %}
    {% endwith %}

    <form method="POST" action="/login" style="justify-content: space-between;">
        <div class="field">
            <div class="control">
                <select class="input is-large" id="role" name="role" placeholder="Your Role" autofocus="">
                    {% for level in level %}
                    <option value="{{level.name}}">{{level.name}}</option>
                    {% endfor %}
                </select>
            </div>
        </div>

        <div class="field">
            <div class="control">
                <input class="input is-large" type="password" name="password" placeholder="Your Password">
            </div>
        </div>
        <div class="field">
            <label class="checkbox">
                <input type="checkbox" name="remember">
                Remember me
                </label>
        </div>
        <button class="button is-block is-info is-large is-fullwidth">Login</button>
    
    </form>
    
    </div>
</div>
{% endblock %}

app/templates/macros.html
{% macro display_tags(deposit) %}
    <div class="tags">
        <p>
        {% for tag in deposit.event %}
         <a href="{{ url_for('community.contribute', tag_name=tag.name) }}" style="text-decoration: none; color: #dd5b5b">
           {{ tag.name }}
         </a>
          |
          {%endfor%}
        </p>
    </div>
{% endmacro %}

app/templates/maloc.html
{% maloc display_register(deposit) %}
    <div class="tags">
        <p>
            {% for member in deposit.member %}
                <a href="{{ url_for('deposit.deposit', depo_id=member.id) }}">{{ member.firstname}} {{ member.lastname}}</a>
                {% for tag in deposit.contribute %}
                <a href="{{ url_for('account.contribute', tag_name=tag.name) }}" style="text-decoration: none; color: #dd5b5b">
                    {{ tag.name }}
                </a>
                |
                {%endfor%}
            {% endfor %}
        </p>
    </div>
{% endmaloc %}

app/templates/other.html
{% extends "base.html" %}

{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
  <link rel="stylesheet" href="{{url_for('static', filename='css/image.css')}}">
{% endblock %}

{% block content %}
<form enctype="multipart/form-data" method="POST">
  <input name="image" type="file"/>
  <input type="submit"/>
</form>

{% endblock%}

app/templates/profile.html
{% extends "base.html" %}
{% block styles %}
  {{ super() }}
  <link rel="stylesheet" href="{{url_for('static', filename='css/styles.css')}}">
{% endblock %}

{% block content %}

{% if image_list|length == 0 %}
  <p>Add some Images to the Gallery</p>
  {% else %}
  {% for image in image_list %}
  <figure><img style="float: left;height: 100px; border-radius: 15%;" src="data:;base64,{{image}}" alt="user"><figcaption></figcaption></figure><br><br>
  {%endfor%}
  {%endif%} 
  <a href="{{url_for('main.uploadNew', img_id=img.id)}}" style="float: right;"><button>upload new image</button></a>
<h1 class="title">
  <br><br><br>
  <b>Welcome, {{ name }}!</b>
  <br>
</h1>
<div class="content">
Role: {{ email.name }}<br>
Contact: {{ contact }} <br>
</div></b>
<span class="title"><h1 style="color: black;">{% block title %} GAMEROCK WELFARE ASSOCIATION {% endblock %}</h1></span>
    <div>
        
      <hr>

        <a href="{{ url_for('register.index')}}"><button>Members </button></a> 
        <!-- <a href="{{url_for('account.index')}}"><button>Contribution Accounts</button></a><br><br> -->
        <a href="{{url_for('register.create')}}"><button>New Member</button></a><br><br>
        <a href="{{ url_for('community.index') }}"><button>Contributions</button></a>
        <a href="{{ url_for('community.add_event') }}"><button>Community Event</button></a>
    </div>
{% endblock %}

app/templates/signup.html
{% extends "base.html" %}
<span class="title"><h1>{% block title %} signup {% endblock %}</h1></span>

{% block content %}
<div class="column is-4 is-offset-4" style="justify-content: center;">
    <br><br>
    <h3 class="title">Sign Up</h3>
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="notification is-danger">
                {{ messages[0] }}. Go to <a href="{{ url_for('auth.login')}}"> login page</a>
            </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/signup" style="justify-content: center;">
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="surname" placeholder="surname" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="first_name" placeholder="firstname" autofocus="">
                </div>
            </div>

            <div class="field">
                <div class="control">
                    <input class="input is-large" type="number" name="phone_num" placeholder="Phone Number">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" type="text" name="username" placeholder="username" autofocus="">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <input class="input is-large" id="myInput" type="password" name="password" placeholder="Password">
                </div>
            </div>
            <div class="field">
                <div class="control">
                    <select class="input is-large" id="role" name="role" placeholder="Role" autofocus="">
                        {% for level in level %}
                        <option value="{{level.name}}">{{level.name}}: {{level.value}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
            
            <input type="checkbox" onclick="myPassword()">Show Password

            <script type="text/javascript" src="{{ url_for('static', filename='js/showPassword.js')}}"></script><br>

            <button class="button is-block is-info is-large is-fullwidth">Sign Up</button>
        </form>
    </div>
</div>
{% endblock %}